/**
 * API Catalog — SATU SUMBER KEBENARAN untuk seluruh dokumentasi API.
 *
 * Semua data endpoint didefinisikan di sini, lalu:
 *   - config/swaggerSpec.js  → generateOpenApiSpec() derive dari sini
 *   - server.js /api/v1/catalog → dikonsumsi frontend (playground, home, /endpoints)
 *
 * JANGAN definisikan ulang endpoint di tempat lain. Tambah endpoint = tambah di sini.
 *
 * Shape param:
 *   { key, in: 'query'|'path', required?, type: 'text'|'number'|'select'|'boolean',
 *     label?, default?, options? (untuk select), placeholder?, description? }
 * default native-typed (number/boolean); frontend String()-kan saat render.
 */

export const IMAMS = ['bukhari', 'muslim', 'tirmidzi', 'abudaud', 'nasai', 'ibnumajah', 'ahmad', 'malik', 'darimi'];

const WIRID_CATEGORIES = ['wirid-harian', 'ratib', 'hizib', 'shalawat', 'istighotsah-mujahadah', 'munajat', 'manaqib-syekh-abdul-qadir', 'dalailul-khairat'];
const DOA_CATEGORIES = ['doa-keseharian', 'doa-rezeki', 'doa-tolak-bala', 'doa-kesehatan', 'doa-perjalanan', 'doa-ilmu', 'doa-waktu-tertentu', 'doa-kualitas-diri', 'doa-pernikahan-rumah-tangga', 'doa-hamil-persalinan', 'doa-wudhu', 'doa-para-nabi-di-al-quran', 'doa-baca-al-quran', 'doa-shalat', 'doa-haji-umrah', 'doa-kematian'];
const MAULID_CATEGORIES = ['maulid-dibai', 'maulidul-barzanji', 'syaraful-anam', 'maulid-simthud-duror', 'qasidah-burdah', 'adl-dliyaul-lami', 'maulid-al-azab'];
const YT_QUALITIES = ['360', '480', '720', '1080'];

/** Helper param pagination (page + limit) — dipakai banyak endpoint. */
function pagination(pageDefault = 1, limitDefault = 20) {
  return [
    { key: 'page', in: 'query', type: 'number', label: 'Halaman', default: pageDefault, description: 'Nomor halaman' },
    { key: 'limit', in: 'query', type: 'number', label: 'Batas (Limit)', default: limitDefault, description: 'Jumlah data per halaman' },
  ];
}

/** Helper param URL wajib — dipakai semua downloader & detail. */
function urlParam(defaultUrl, placeholder, label = 'URL') {
  return {
    key: 'url', in: 'query', required: true, type: 'text', label,
    default: defaultUrl, placeholder,
    description: 'URL lengkap yang ingin diekstrak',
  };
}

export const API_CATEGORIES = [
  { key: 'hadits', label: 'Hadits Digital', swaggerTag: 'Hadits Digital 9 Imam', icon: 'fa-solid fa-book-quran', description: 'Database Hadits SQLite FTS5: Bukhari, Muslim, Abu Daud, Tirmidzi, Nasai, Ibnu Majah, Ahmad, Malik, Darimi' },
  { key: 'islami', label: 'Layanan Islami', swaggerTag: 'Layanan Islami', icon: 'fa-solid fa-kaaba', description: 'Al-Qur’an Digital, Jadwal Sholat Indonesia, Khutbah MUI, Tahlil & Doa Tahlil, Wirid/Ratib/Hizib, Maulid Nabi, Doa Islami, & Arsip Dokumen NU' },
  { key: 'budaya', label: 'Budaya & Aksara', swaggerTag: 'Budaya & Aksara', icon: 'fa-solid fa-scroll', description: 'Transliterasi Aksara Jawa Native (Latin ↔ Aksara Jawa)' },
  { key: 'lirik', label: 'Lirik Musik', swaggerTag: 'Lirik Musik', icon: 'fa-solid fa-music', description: 'Database lirik lagu: pencarian & lirik time-synced (LRC)' },
  { key: 'info', label: 'Informasi & Cuaca', swaggerTag: 'Informasi & Cuaca', icon: 'fa-solid fa-cloud-bolt', description: 'Data gempa bumi & prakiraan cuaca realtime dari BMKG, IP Info, Ping & WHOIS' },
  { key: 'anime', label: 'Anime & Donghua', swaggerTag: 'Anime & Streaming', icon: 'fa-solid fa-tv', description: 'Scraper streaming & episode anime/donghua Sub Indo (Animasu & AniChin)' },
  { key: 'manga', label: 'Manga & Komik', swaggerTag: 'Manga & Komik', icon: 'fa-solid fa-book-open', description: 'Manga reader, daftar chapter & image proxy anti-403 (Komiku)' },
  { key: 'pendidikan', label: 'Data Pendidikan', swaggerTag: 'Data Pendidikan', icon: 'fa-solid fa-graduation-cap', description: 'Pencarian dan detail data mahasiswa, dosen, perguruan tinggi, serta program studi dari PDDIKTI Kemdiktisaintek' },
  { key: 'downloader', label: 'Media Downloader', swaggerTag: 'Media Downloader', icon: 'fa-solid fa-download', description: 'Extractor media multi-platform: Instagram, Facebook, Threads, YouTube, Twitter/X, TikTok, Mediafire' },
];

export const API_ENDPOINTS = [
  // ================= HADITS DIGITAL 9 IMAM =================
  {
    key: 'books',
    name: 'List Kitab Hadits (Ringkasan)',
    category: 'hadits',
    path: '/api/v1/hadits/books',
    methods: ['GET'],
    summary: 'Ringkasan 9 Kitab Hadits',
    description: 'Mendapatkan statistik total hadits dari 9 perawi imam (Bukhari, Muslim, Abu Daud, Tirmidzi, Nasai, Ibnu Majah, Ahmad, Malik, Darimi).',
    card: { tag: 'Hadits' },
    params: [],
  },
  {
    key: 'hadits-search',
    name: 'Pencarian Hadits (SQLite FTS)',
    category: 'hadits',
    path: '/api/v1/hadits/search',
    methods: ['GET'],
    summary: 'Search FTS Hadits',
    description: 'Pencarian cepat kata kunci pada teks terjemahan hadits menggunakan mesin SQLite Full-Text Search (FTS5).',
    card: { tag: 'Hadits' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci (q)', default: 'niat', placeholder: 'contoh: niat, shalat, puasa', description: 'Kata kunci pencarian terjemahan hadits' },
      ...pagination(1, 5),
    ],
  },
  {
    key: 'hadits-single',
    name: 'Detail Hadits Spesifik',
    category: 'hadits',
    path: '/api/v1/hadits/{imam}/{number}',
    methods: ['GET'],
    summary: 'Single Hadits Detail',
    description: 'Mengambil detail spesifik hadits beserta bab, kitab, dan terjemahan berdasarkan perawi imam dan nomor hadits.',
    card: { tag: 'Hadits' },
    params: [
      { key: 'imam', in: 'path', required: true, type: 'select', options: IMAMS, label: 'Perawi / Imam', default: 'bukhari', description: 'Nama perawi imam' },
      { key: 'number', in: 'path', required: true, type: 'number', label: 'Nomor Hadits', default: 1, description: 'Nomor urut hadits' },
    ],
  },
  {
    key: 'hadits-list',
    name: 'Daftar Hadits Per Imam (Paginated)',
    category: 'hadits',
    path: '/api/v1/hadits/{imam}',
    methods: ['GET'],
    summary: 'Daftar Hadits Per Perawi',
    description: 'Mendapatkan daftar hadits per perawi imam secara berurutan dengan fitur paginasi (limit & page).',
    card: { tag: 'Hadits' },
    params: [
      { key: 'imam', in: 'path', required: true, type: 'select', options: IMAMS, label: 'Perawi / Imam', default: 'muslim', description: 'Nama perawi imam' },
      ...pagination(1, 5),
    ],
  },

  // ================= LAYANAN ISLAMI =================
  {
    key: 'sholat-jadwal',
    name: 'Jadwal Sholat Harian & Bulanan',
    category: 'islami',
    path: '/api/v1/sholat/jadwal',
    methods: ['GET'],
    summary: 'Jadwal Sholat Harian & Bulanan',
    description: 'Mengambil jadwal sholat lengkap (Imsak, Subuh, Terbit, Dhuha, Dzuhur, Ashar, Maghrib, Isya) berdasarkan kota/kabupaten di Indonesia.',
    card: { tag: 'Jadwal Sholat' },
    params: [
      { key: 'kota', in: 'query', required: true, type: 'text', label: 'Nama Kota / Daerah', default: 'Jakarta Pusat', placeholder: 'contoh: Jakarta Pusat, Bandung, Surabaya', description: 'Nama atau ID kota' },
      { key: 'bulan', in: 'query', type: 'number', label: 'Bulan (1-12)', default: 8, description: 'Bulan jadwal (1-12)' },
      { key: 'tahun', in: 'query', type: 'number', label: 'Tahun', default: 2026, description: 'Tahun jadwal' },
    ],
  },
  {
    key: 'sholat-kota',
    name: 'Daftar ID Kota Sholat',
    category: 'islami',
    path: '/api/v1/sholat/kota',
    methods: ['GET'],
    summary: 'Daftar ID Kota Sholat',
    description: 'Mendapatkan seluruh daftar ID kota di Indonesia beserta opsi pencarian berdasarkan nama kota.',
    card: { tag: 'Jadwal Sholat' },
    params: [
      { key: 'q', in: 'query', type: 'text', label: 'Cari Nama Kota (Opsional)', default: 'Bandung', placeholder: 'contoh: Jakarta, Bandung, Surabaya', description: 'Nama kota untuk filter' },
    ],
  },
  {
    key: 'quran-surat-list',
    name: 'Daftar Surah Al-Qur’an',
    category: 'islami',
    path: '/api/v1/quran/surat',
    methods: ['GET'],
    summary: 'Daftar 114 Surah Al-Qur’an',
    description: 'Mendapatkan daftar seluruh 114 surah Al-Qur’an lengkap dengan nama Arab, Latin, terjemahan, jumlah ayat, dan nomor urut.',
    card: { tag: 'Al-Qur’an' },
    params: [],
  },
  {
    key: 'quran-surat-detail',
    name: 'Detail Surah (Ayat-ayat)',
    category: 'islami',
    path: '/api/v1/quran/surat/{nomor}',
    methods: ['GET'],
    summary: 'Detail Surah + Ayat, Terjemahan & Audio',
    description: 'Mendapatkan isi satu surah lengkap dengan teks Arab, latin, terjemahan, audio per ayat, dan informasi surah.',
    card: { tag: 'Al-Qur’an' },
    params: [
      { key: 'nomor', in: 'path', required: true, type: 'number', label: 'Nomor Surah', default: 1, description: 'Nomor surah (1-114)' },
    ],
  },
  {
    key: 'quran-tafsir',
    name: 'Tafsir Surah',
    category: 'islami',
    path: '/api/v1/quran/tafsir/{nomor}',
    methods: ['GET'],
    summary: 'Tafsir Kemenag per Surah',
    description: 'Mendapatkan tafsir ayat-ayat suatu surah dari Kementerian Agama RI.',
    card: { tag: 'Al-Qur’an' },
    params: [
      { key: 'nomor', in: 'path', required: true, type: 'number', label: 'Nomor Surah', default: 1, description: 'Nomor surah (1-114)' },
    ],
  },
  {
    key: 'quran-search',
    name: 'Pencarian Ayat Al-Qur’an',
    category: 'islami',
    path: '/api/v1/quran/search',
    methods: ['GET'],
    summary: 'Cari Ayat Berdasarkan Kata Kunci',
    description: 'Mencari ayat Al-Qur’an berdasarkan kata kunci di terjemahan Bahasa Indonesia, dengan teks Arab + terjemahan dan paginasi.',
    card: { tag: 'Al-Qur’an' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci', default: 'rahmat', placeholder: 'contoh: rahmat, sabar, rezeki', description: 'Kata kunci pencarian ayat' },
      { key: 'page', in: 'query', type: 'number', label: 'Halaman', default: 1, description: 'Nomor halaman hasil pencarian' },
      { key: 'size', in: 'query', type: 'number', label: 'Jumlah per Halaman', default: 10, description: 'Jumlah hasil per halaman (1-50)' },
    ],
  },
  {
    key: 'khutbah-list',
    name: 'Kumpulan Khutbah MUI',
    category: 'islami',
    path: '/api/v1/khutbah',
    methods: ['GET'],
    summary: 'Kumpulan Khutbah MUI',
    description: 'Mendapatkan daftar artikel naskah Khutbah Jumat & Idul Fitri resmi terbaru dari Majelis Ulama Indonesia (MUI).',
    card: { tag: 'Khutbah MUI' },
    params: [
      ...pagination(1, 20),
    ],
  },
  {
    key: 'khutbah-detail',
    name: 'Detail Naskah Khutbah MUI',
    category: 'islami',
    path: '/api/v1/khutbah/detail',
    methods: ['GET'],
    summary: 'Detail Naskah Khutbah MUI',
    description: 'Mengambil isi teks naskah lengkap artikel khutbah berdasarkan URL naskah MUI.',
    card: { tag: 'Khutbah MUI' },
    params: [
      { key: 'url', in: 'query', required: true, type: 'text', label: 'URL Naskah Khutbah MUI', default: 'https://mui.or.id/baca/khutbah/khutbah-jumat-mewaspadai-virus-takabur', placeholder: 'https://mui.or.id/baca/khutbah/...', description: 'URL artikel khutbah MUI' },
    ],
  },
  {
    key: 'wirid',
    name: 'Bacaan Wirid, Ratib & Hizib',
    category: 'islami',
    path: '/api/v1/wirid',
    methods: ['GET'],
    summary: 'Bacaan Wirid, Ratib & Hizib',
    description: 'Kumpulan teks bacaan Wirid Harian, Ratib (al-Haddad, al-Athas), Hizib, Shalawat, Istighotsah, dan Asmaul Husna lengkap teks Arab & Terjemahan.',
    card: { tag: 'Wirid & Dzikir' },
    params: [
      { key: 'category', in: 'query', type: 'select', options: WIRID_CATEGORIES, label: 'Kategori Wirid & Dzikir', default: 'ratib', description: 'Kategori bacaan wirid' },
    ],
  },
  {
    key: 'doa',
    name: 'Doa Harian & Pilihan',
    category: 'islami',
    path: '/api/v1/doa',
    methods: ['GET'],
    summary: 'Doa Harian & Pilihan',
    description: 'Kumpulan doa keseharian, doa rezeki, tolak bala, kesehatan, doa para nabi, pernikahan, dan doa shalat lengkap teks Arab & Terjemahan.',
    card: { tag: 'Doa Islami' },
    params: [
      { key: 'category', in: 'query', type: 'select', options: DOA_CATEGORIES, label: 'Kategori Doa', default: 'doa-keseharian', description: 'Kategori doa islami' },
    ],
  },
  {
    key: 'maulid',
    name: 'Teks Kitab Maulid Nabi',
    category: 'islami',
    path: '/api/v1/maulid',
    methods: ['GET'],
    summary: 'Teks Kitab Maulid Nabi',
    description: 'Kumpulan teks bacaan Kitab Maulid Nabi (Diba\'i, Barzanji, Syarafil Anam, Simthud Durar, Burdah, Adl-Dliyaul Lami\', Maulid \'Azab) lengkap teks Arab, Latin, dan Terjemahan dari NU Online.',
    card: { tag: 'Maulid Nabi' },
    params: [
      { key: 'category', in: 'query', type: 'select', options: MAULID_CATEGORIES, label: 'Kitab Maulid', default: 'maulid-dibai', description: 'Slug kitab maulid yang ingin dibaca' },
    ],
  },
  {
    key: 'maulid-books',
    name: 'Daftar Kitab Maulid Nabi',
    category: 'islami',
    path: '/api/v1/maulid/books',
    methods: ['GET'],
    summary: 'Daftar Kitab Maulid',
    description: 'Mendapatkan daftar 7 Kitab Maulid Nabi yang tersedia di NU Online beserta pengarang dan total bacaan.',
    card: { tag: 'Maulid Nabi' },
    params: [],
  },
  {
    key: 'tahlil',
    name: 'Bacaan Tahlil & Doa Arwah',
    category: 'islami',
    path: '/api/v1/tahlil',
    methods: ['GET'],
    summary: 'Susunan Bacaan Tahlil Lengkap',
    description: 'Susunan lengkap 56 bacaan Tahlil dan Doa Tahlil/Arwah NU Online dilengkapi teks Arab, transliterasi Latin, dan terjemahan bahasa Indonesia.',
    card: { tag: 'Tahlil' },
    params: [
      { key: 'number', in: 'query', type: 'number', label: 'Nomor Urut', placeholder: '1', description: 'Filter langsung ke nomor urut bacaan tahlil (1-56)' },
      ...pagination(1, 56),
    ],
  },
  {
    key: 'tahlil-detail',
    name: 'Detail Bacaan Tahlil (Nomor)',
    category: 'islami',
    path: '/api/v1/tahlil/{number}',
    methods: ['GET'],
    summary: 'Detail Butir Bacaan Tahlil',
    description: 'Mendapatkan satu butir bacaan tahlil spesifik berdasarkan nomor urut (1-56).',
    card: { tag: 'Tahlil' },
    params: [
      { key: 'number', in: 'path', required: true, type: 'number', label: 'Nomor Butir', default: 1, description: 'Nomor butir bacaan tahlil (1-56)' },
    ],
  },
  {
    key: 'nu-download',
    name: 'Arsip Dokumen & Media NU Online',
    category: 'islami',
    path: '/api/v1/nu-download',
    methods: ['GET'],
    summary: 'Arsip Dokumen & Media NU Online',
    description: 'Mengunduh dokumen resmi, buku/kitab, amaliyah, produk hukum (fatwa/bahtsul masail), serta audio mars & himne NU Online (MP3/PDF).',
    card: { tag: 'Layanan Islami' },
    params: [
      { key: 'category', in: 'query', type: 'text', label: 'Kategori Arsip', default: 'lagu-mars-dan-himne', description: 'Kategori arsip NU Online' },
      { key: 'q', in: 'query', type: 'text', label: 'Kata Kunci (Opsional)', default: 'pmii', description: 'Filter pencarian dokumen' },
    ],
  },

  // ================= BUDAYA & AKSARA =================
  {
    key: 'aksara-latin',
    name: 'Latin ke Aksara Jawa Transliteration',
    category: 'budaya',
    path: '/api/v1/aksara/latin-to-jawa',
    methods: ['GET'],
    summary: 'Latin ke Aksara Jawa',
    description: 'Transliterasi teks Latin ke Aksara Jawa native (sub-millisecond latency) lengkap dengan opsi Sandhangan & Aksara Murda.',
    card: { tag: 'Aksara Jawa' },
    params: [
      { key: 'text', in: 'query', required: true, type: 'text', label: 'Teks Latin', default: 'sugeng enjang', placeholder: 'masukkan teks latin...', description: 'Teks Latin yang akan dikonversi' },
      { key: 'murda', in: 'query', type: 'select', options: ['false', 'true'], label: 'Aksara Murda (Kapital)', default: 'false', description: 'Aktifkan Aksara Murda' },
    ],
  },
  {
    key: 'aksara-jawa',
    name: 'Aksara Jawa ke Latin Transliteration',
    category: 'budaya',
    path: '/api/v1/aksara/jawa-to-latin',
    methods: ['GET'],
    summary: 'Aksara Jawa ke Latin',
    description: 'Mengubah teks Unicode Aksara Jawa kembali menjadi alfabet Latin secara instan.',
    card: { tag: 'Aksara Jawa' },
    params: [
      { key: 'text', in: 'query', required: true, type: 'text', label: 'Teks Aksara Jawa', default: 'ꦱꦸꦒꦼꦁ ꦲꦺꦤ꧀ꦗꦁ', placeholder: 'masukkan aksara jawa...', description: 'Teks Aksara Jawa yang akan dikonversi' },
    ],
  },

  // ================= LIRIK MUSIK =================
  {
    key: 'lirik-search',
    name: 'Cari Lirik Lagu',
    category: 'lirik',
    path: '/api/v1/lirik/search',
    methods: ['GET'],
    summary: 'Cari Lirik Lagu',
    description: 'Mencari lirik lagu berdasarkan kata kunci bebas atau judul/artis/album spesifik. Mengembalikan daftar lagu beserta lirik plain dan time-synced (LRC).',
    card: { tag: 'Lirik Lagu' },
    params: [
      { key: 'q', in: 'query', type: 'text', label: 'Kata Kunci / Judul', default: 'shalawat', placeholder: 'contoh: shalawat, lagu religi', description: 'Kata kunci bebas (judul/artis/album)' },
      { key: 'judul', in: 'query', type: 'text', label: 'Judul (Opsional)', description: 'Filter judul lagu spesifik' },
      { key: 'artis', in: 'query', type: 'text', label: 'Artis (Opsional)', description: 'Filter nama artis spesifik' },
      { key: 'album', in: 'query', type: 'text', label: 'Album (Opsional)', description: 'Filter nama album' },
    ],
  },
  {
    key: 'lirik-detail',
    name: 'Ambil Lirik Lagu Spesifik',
    category: 'lirik',
    path: '/api/v1/lirik',
    methods: ['GET'],
    summary: 'Ambil Lirik Lagu Spesifik',
    description: 'Mengambil lirik (plain + time-synced LRC) untuk lagu spesifik berdasarkan judul dan artis. Akurasi meningkat dengan album & durasi.',
    card: { tag: 'Lirik Lagu' },
    params: [
      { key: 'judul', in: 'query', required: true, type: 'text', label: 'Judul Lagu', default: 'Bohemian Rhapsody', description: 'Judul lagu' },
      { key: 'artis', in: 'query', required: true, type: 'text', label: 'Nama Artis', default: 'Queen', description: 'Nama artis' },
      { key: 'album', in: 'query', type: 'text', label: 'Album (Opsional)', description: 'Nama album (opsional)' },
      { key: 'durasi', in: 'query', type: 'number', label: 'Durasi (Detik)', default: 354, description: 'Durasi lagu dalam detik (tingkatkan akurasi)' },
    ],
  },

  // ================= INFORMASI & CUACA (BMKG) =================
  {
    key: 'bmkg_gempa',
    name: 'BMKG Info Gempa Realtime',
    category: 'info',
    path: '/api/v1/bmkg/gempa',
    methods: ['GET'],
    summary: 'Info Gempa BMKG Realtime',
    description: 'Data gempa bumi terbaru M 5.0+, potensi tsunami, dan peta guncangan (shakemap) dari BMKG.',
    card: { tag: 'Informasi & Cuaca' },
    params: [],
  },
  {
    key: 'bmkg_gempa-dirasakan',
    name: 'BMKG Daftar Gempa Dirasakan',
    category: 'info',
    path: '/api/v1/bmkg/gempa-dirasakan',
    methods: ['GET'],
    summary: 'Daftar Gempa Dirasakan BMKG',
    description: 'Daftar gempa bumi terbaru yang dirasakan masyarakat dari BMKG.',
    card: { tag: 'Informasi & Cuaca' },
    params: [],
  },
  {
    key: 'bmkg_cuaca',
    name: 'BMKG Prakiraan Cuaca Per Desa / Kelurahan',
    category: 'info',
    path: '/api/v1/bmkg/cuaca',
    methods: ['GET'],
    summary: 'Prakiraan Cuaca Per Desa / Kelurahan BMKG',
    description: 'Prakiraan cuaca presisi tingkat desa/kelurahan dari server resmi BMKG Indonesia. Bisa pakai nama lokasi (desa,kecamatan,kota,provinsi) atau kode adm4.',
    card: { tag: 'Informasi & Cuaca' },
    params: [
      { key: 'desa', in: 'query', type: 'text', label: 'Nama Lokasi (desa,kecamatan,kota,provinsi)', placeholder: 'Purbasari,Karangjambu,Purbalingga,Jawa Tengah', description: 'Nama desa,kecamatan,kota,provinsi dipisah koma. Desa & kecamatan wajib, kota & provinsi opsional.' },
      { key: 'adm4', in: 'query', type: 'text', label: 'Kode Adm4 Desa/Kelurahan (opsional)', default: '31.71.01.1001', placeholder: 'Contoh: 31.71.01.1001', description: 'Kode adm4 desa/kelurahan 10 digit — alternatif bila tak mau pakai nama.' },
    ],
  },

  // ================= INFORMASI & BMKG & CHECKHOST =================
  {
    key: 'bmkg-gempa',
    name: 'BMKG Info Gempa Realtime (M 5.0+ & Dirasakan)',
    category: 'info',
    subcategory: 'bmkg',
    subcategoryLabel: 'BMKG Gempa & Cuaca',
    path: '/api/v1/bmkg/gempa',
    methods: ['GET'],
    summary: 'BMKG Info Gempa',
    description: 'Data gempa bumi terbaru M 5.0+, potensi tsunami, dan peta guncangan (shakemap) dari BMKG.',
    card: { tag: 'BMKG' },
    params: [],
  },
  {
    key: 'bmkg-cuaca',
    name: 'BMKG Prakiraan Cuaca Per Desa / Kelurahan',
    category: 'info',
    subcategory: 'bmkg',
    subcategoryLabel: 'BMKG Gempa & Cuaca',
    path: '/api/v1/bmkg/cuaca',
    methods: ['GET'],
    summary: 'BMKG Prakiraan Cuaca Desa',
    description: 'Prakiraan cuaca presisi tingkat desa/kelurahan dari server resmi BMKG Indonesia.',
    card: { tag: 'BMKG' },
    params: [
      { key: 'adm4', in: 'query', type: 'text', label: 'Kode Adm4 Desa', default: '31.71.01.1001', placeholder: 'contoh: 31.71.01.1001 (Gambir)', description: 'Kode kelurahan/desa adm4' },
    ],
  },
  {
    key: 'checkhost-ipinfo',
    name: 'CheckHost IP & Host Geolocation',
    category: 'info',
    subcategory: 'checkhost',
    subcategoryLabel: 'CheckHost & WHOIS',
    path: '/api/v1/checkhost/ip-info',
    methods: ['GET'],
    summary: 'CheckHost IP Info',
    description: 'Mengambil lokasi geografis, ASN, ISP, timezone, dan kordinat IP/Domain.',
    card: { tag: 'CheckHost' },
    params: [
      { key: 'host', in: 'query', type: 'text', label: 'Host / IP Address', default: 'google.com', placeholder: 'contoh: google.com atau 8.8.8.8', description: 'Domain atau IP target' },
    ],
  },
  {
    key: 'checkhost-ping',
    name: 'CheckHost Global Ping Test',
    category: 'info',
    subcategory: 'checkhost',
    subcategoryLabel: 'CheckHost & WHOIS',
    path: '/api/v1/checkhost/ping',
    methods: ['GET'],
    summary: 'CheckHost Global Ping',
    description: 'Melakukan uji ping ke target dari puluhan server monitoring global.',
    card: { tag: 'CheckHost' },
    params: [
      { key: 'host', in: 'query', type: 'text', label: 'Host Target Ping', default: 'google.com', placeholder: 'contoh: google.com', description: 'Domain atau IP target' },
    ],
  },
  {
    key: 'checkhost-whois',
    name: 'Domain & IP WHOIS Lookup',
    category: 'info',
    subcategory: 'checkhost',
    subcategoryLabel: 'CheckHost & WHOIS',
    path: '/api/v1/checkhost/whois',
    methods: ['GET'],
    summary: 'WHOIS Record Lookup',
    description: 'Mengambil catatan registrasi domain / IP dari database WHOIS resmi.',
    card: { tag: 'WHOIS' },
    params: [
      { key: 'domain', in: 'query', type: 'text', label: 'Domain / IP Target', default: 'google.com', placeholder: 'contoh: google.com', description: 'Domain atau IP target' },
    ],
  },

  // ================= ANIME & DONGHUA (ANIMASU & ANICHIN) =================
  {
    key: 'animasu-home',
    name: 'Animasu Beranda Anime Sub Indo',
    category: 'anime',
    subcategory: 'animasu',
    subcategoryLabel: 'Animasu Stream',
    path: '/api/v1/animasu/home',
    methods: ['GET'],
    summary: 'Animasu Beranda',
    description: 'Mengambil daftar anime sedang tayang (ongoing) dan baru ditambah dari Animasu.',
    card: { tag: 'Animasu' },
    params: [
      { key: 'page', in: 'query', type: 'number', label: 'Halaman', default: 1, description: 'Nomor halaman' },
    ],
  },
  {
    key: 'animasu-search',
    name: 'Animasu Cari Anime',
    category: 'anime',
    subcategory: 'animasu',
    subcategoryLabel: 'Animasu Stream',
    path: '/api/v1/animasu/search',
    methods: ['GET'],
    summary: 'Animasu Search',
    description: 'Mencari judul anime di katalog Animasu.',
    card: { tag: 'Animasu' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci', default: 'naruto', placeholder: 'contoh: naruto', description: 'Judul anime' },
    ],
  },
  {
    key: 'animasu-detail',
    name: 'Animasu Detail Anime & Episode',
    category: 'anime',
    subcategory: 'animasu',
    subcategoryLabel: 'Animasu Stream',
    path: '/api/v1/animasu/detail',
    methods: ['GET'],
    summary: 'Animasu Detail Anime',
    description: 'Mengambil metadata lengkap anime, sinopsis, rating, dan daftar episode.',
    card: { tag: 'Animasu' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Anime', default: 'one-piece-gyojin-tou-hen', placeholder: 'contoh: one-piece-gyojin-tou-hen', description: 'Slug anime' },
    ],
  },
  {
    key: 'animasu-episode',
    name: 'Animasu Stream Player Episode',
    category: 'anime',
    subcategory: 'animasu',
    subcategoryLabel: 'Animasu Stream',
    path: '/api/v1/animasu/episode',
    methods: ['GET'],
    summary: 'Animasu Stream Episode',
    description: 'Mengambil iframe player streaming & mirror server episode anime.',
    card: { tag: 'Animasu' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Episode', default: 'one-piece-gyojin-tou-hen-episode-1-sub-indo', placeholder: 'contoh: one-piece-gyojin-tou-hen-episode-1-sub-indo', description: 'Slug episode' },
    ],
  },
  {
    key: 'anichin-home',
    name: 'AniChin Beranda Donghua Sub Indo',
    category: 'anime',
    subcategory: 'anichin',
    subcategoryLabel: 'AniChin Donghua',
    path: '/api/v1/anichin/home',
    methods: ['GET'],
    summary: 'AniChin Beranda Donghua',
    description: 'Mengambil daftar rilis Donghua terbaru dan serial ongoing dari AniChin.',
    card: { tag: 'AniChin' },
    params: [],
  },
  {
    key: 'anichin-search',
    name: 'AniChin Cari Donghua',
    category: 'anime',
    subcategory: 'anichin',
    subcategoryLabel: 'AniChin Donghua',
    path: '/api/v1/anichin/search',
    methods: ['GET'],
    summary: 'AniChin Search Donghua',
    description: 'Mencari judul Donghua Subtitle Indonesia di catalog AniChin.',
    card: { tag: 'AniChin' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci Donghua', default: 'soul land', placeholder: 'contoh: soul land', description: 'Judul Donghua' },
    ],
  },
  {
    key: 'anichin-detail',
    name: 'AniChin Detail Donghua & Episode',
    category: 'anime',
    subcategory: 'anichin',
    subcategoryLabel: 'AniChin Donghua',
    path: '/api/v1/anichin/detail',
    methods: ['GET'],
    summary: 'AniChin Detail Donghua',
    description: 'Mengambil metadata lengkap Donghua, sinopsis, genre, dan 100+ daftar episode.',
    card: { tag: 'AniChin' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Donghua', default: 'soul-land-2-the-unrivaled-tang-sect', placeholder: 'contoh: soul-land-2-the-unrivaled-tang-sect', description: 'Slug Donghua' },
    ],
  },
  {
    key: 'anichin-episode',
    name: 'AniChin Stream Player Episode',
    category: 'anime',
    subcategory: 'anichin',
    subcategoryLabel: 'AniChin Donghua',
    path: '/api/v1/anichin/episode',
    methods: ['GET'],
    summary: 'AniChin Stream Episode',
    description: 'Dekode otomatis iframe player streaming & mirror server (OK.ru, Premium, Drive, dll).',
    card: { tag: 'AniChin' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Episode', default: 'soul-land-2-the-unrivaled-tang-sect-episode-164-subtitle-indonesia', placeholder: 'contoh: soul-land-2-...-episode-164...', description: 'Slug episode Donghua' },
    ],
  },
  {
    key: 'otakudesu-home',
    name: 'Otakudesu Beranda Anime Sub Indo',
    category: 'anime',
    subcategory: 'otakudesu',
    subcategoryLabel: 'Otakudesu Anime',
    path: '/api/v1/otakudesu/home',
    methods: ['GET'],
    summary: 'Otakudesu Beranda',
    description: 'Mengambil daftar anime ongoing & completed terbaru dari Otakudesu.',
    card: { tag: 'Otakudesu' },
    params: [],
  },
  {
    key: 'otakudesu-schedule',
    name: 'Otakudesu Jadwal Rilis Anime',
    category: 'anime',
    subcategory: 'otakudesu',
    subcategoryLabel: 'Otakudesu Anime',
    path: '/api/v1/otakudesu/schedule',
    methods: ['GET'],
    summary: 'Otakudesu Jadwal Rilis',
    description: 'Mengambil jadwal rilis anime harian (Senin - Minggu) dari Otakudesu.',
    card: { tag: 'Otakudesu' },
    params: [],
  },
  {
    key: 'otakudesu-search',
    name: 'Otakudesu Cari Anime',
    category: 'anime',
    subcategory: 'otakudesu',
    subcategoryLabel: 'Otakudesu Anime',
    path: '/api/v1/otakudesu/search',
    methods: ['GET'],
    summary: 'Otakudesu Search',
    description: 'Mencari judul anime Subtitle Indonesia di catalog Otakudesu.',
    card: { tag: 'Otakudesu' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci', default: 'one piece', placeholder: 'contoh: one piece, boruto', description: 'Judul anime' },
    ],
  },
  {
    key: 'otakudesu-detail',
    name: 'Otakudesu Detail Anime & Daftar Episode',
    category: 'anime',
    subcategory: 'otakudesu',
    subcategoryLabel: 'Otakudesu Anime',
    path: '/api/v1/otakudesu/detail',
    methods: ['GET'],
    summary: 'Otakudesu Detail Anime',
    description: 'Mengambil metadata lengkap anime, skor, produser, studio, sinopsis, dan daftar episode.',
    card: { tag: 'Otakudesu' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Anime', default: '1piece-sub-indo', placeholder: 'contoh: 1piece-sub-indo', description: 'Slug anime Otakudesu' },
    ],
  },
  {
    key: 'otakudesu-episode',
    name: 'Otakudesu Stream Player & Mirror List',
    category: 'anime',
    subcategory: 'otakudesu',
    subcategoryLabel: 'Otakudesu Anime',
    path: '/api/v1/otakudesu/episode',
    methods: ['GET'],
    summary: 'Otakudesu Stream Episode',
    description: 'Mengambil iframe player default dan daftar mirror server streaming per episode.',
    card: { tag: 'Otakudesu' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Episode', default: 'wpoiec-episode-1178-sub-indo', placeholder: 'contoh: wpoiec-episode-1178-sub-indo', description: 'Slug episode Otakudesu' },
    ],
  },

  // ================= MANGA & KOMIK (KOMIKU) =================
  {
    key: 'komiku-home',
    name: 'Komiku Beranda & Ranking Komik',
    category: 'manga',
    subcategory: 'komiku',
    subcategoryLabel: 'Komiku Reader',
    path: '/api/v1/komiku/home',
    methods: ['GET'],
    summary: 'Komiku Beranda',
    description: 'Mengambil daftar komik rekomendasi/ranking dan terbitan terbaru dari Komiku.org.',
    card: { tag: 'Komiku' },
    params: [],
  },
  {
    key: 'komiku-detail',
    name: 'Komiku Detail Komik & Daftar Chapter',
    category: 'manga',
    subcategory: 'komiku',
    subcategoryLabel: 'Komiku Reader',
    path: '/api/v1/komiku/detail',
    methods: ['GET'],
    summary: 'Komiku Detail Komik',
    description: 'Mengambil metadata komik, pengarang, genre, sinopsis, dan 400+ daftar chapter.',
    card: { tag: 'Komiku' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Komik', default: 'tomb-raider-king', placeholder: 'contoh: tomb-raider-king', description: 'Slug komik' },
    ],
  },
  {
    key: 'komiku-chapter',
    name: 'Komiku Baca Chapter Komik',
    category: 'manga',
    subcategory: 'komiku',
    subcategoryLabel: 'Komiku Reader',
    path: '/api/v1/komiku/chapter',
    methods: ['GET'],
    summary: 'Komiku Baca Chapter',
    description: 'Mengambil seluruh URL gambar halaman chapter komik lengkap dengan URL proxy anti-403 hotlink.',
    card: { tag: 'Komiku' },
    params: [
      { key: 'slug', in: 'query', required: true, type: 'text', label: 'Slug Chapter', default: 'tomb-raider-king-chapter-411', placeholder: 'contoh: tomb-raider-king-chapter-411', description: 'Slug chapter komik' },
    ],
  },
  {
    key: 'komiku-proxy',
    name: 'Komiku Image Anti-Hotlink Proxy',
    category: 'manga',
    subcategory: 'komiku',
    subcategoryLabel: 'Komiku Reader',
    path: '/api/v1/komiku/proxy-image',
    methods: ['GET'],
    summary: 'Komiku Image Proxy',
    description: 'Streaming gambar halaman komik dari img.komiku.org secara langsung dengan injection Referer valid (Bypass 403 Forbidden).',
    card: { tag: 'Komiku' },
    params: [
      { key: 'url', in: 'query', required: true, type: 'text', label: 'URL Gambar Original', default: 'https://img.komiku.org/upload5/tomb-raider-king/411/2026-05-28/1.png', placeholder: 'https://img.komiku.org/...', description: 'URL gambar dari img.komiku.org' },
    ],
  },

  {
    key: 'tv-channels',
    name: 'Daftar Stasiun TV Nasional',
    category: 'info',
    subcategory: 'tv',
    subcategoryLabel: 'Jadwal TV & Bola',
    path: '/api/v1/tv/channels',
    methods: ['GET'],
    summary: 'Daftar Channel TV',
    description: 'Mengambil seluruh daftar ID channel TV nasional Indonesia dari JadwalTV.net.',
    card: { tag: 'Jadwal TV' },
    params: [],
  },
  {
    key: 'tv-schedule',
    name: 'Jadwal Acara TV Per Channel',
    category: 'info',
    subcategory: 'tv',
    subcategoryLabel: 'Jadwal TV & Bola',
    path: '/api/v1/tv/schedule',
    methods: ['GET'],
    summary: 'Jadwal TV Per Channel',
    description: 'Mengambil susunan jadwal jam tayang acara TV berdasarkan ID channel (RCTI, TransTV, SCTV, Indosiar, dll).',
    card: { tag: 'Jadwal TV' },
    params: [
      { key: 'channel', in: 'query', required: true, type: 'text', label: 'ID Channel TV', default: 'rcti', placeholder: 'contoh: rcti, transtv, sctv, indosiar', description: 'ID channel TV' },
    ],
  },
  {
    key: 'tv-now',
    name: 'Jadwal Acara TV Nasional Saat Ini',
    category: 'info',
    subcategory: 'tv',
    subcategoryLabel: 'Jadwal TV & Bola',
    path: '/api/v1/tv/now',
    methods: ['GET'],
    summary: 'Jadwal TV Saat Ini',
    description: 'Mengambil daftar acara yang sedang tayang di seluruh stasiun TV nasional saat ini secara realtime.',
    card: { tag: 'Jadwal TV' },
    params: [],
  },
  {
    key: 'tv-football',
    name: 'Jadwal Siaran Langsung Sepakbola',
    category: 'info',
    subcategory: 'tv',
    subcategoryLabel: 'Jadwal TV & Bola',
    path: '/api/v1/tv/football',
    methods: ['GET'],
    summary: 'Jadwal Live Sepakbola',
    description: 'Mengambil jadwal siaran langsung pertandingan sepakbola liga dunia di TV nasional & streaming.',
    card: { tag: 'Sepakbola' },
    params: [],
  },

  // ================= KERETA COMMUTER LINE (KCI) =================
  {
    key: 'kci-stations',
    name: 'Daftar Stasiun KRL Commuter Line',
    category: 'info',
    subcategory: 'kci',
    subcategoryLabel: 'Jadwal KRL Commuter Line',
    path: '/api/v1/kci/stations',
    methods: ['GET'],
    summary: 'Daftar Stasiun KRL',
    description: 'Mengambil seluruh daftar kode & nama stasiun KRL Commuter Line (Jabodetabek, Jogja-Solo, Merak).',
    card: { tag: 'KRL Commuter' },
    params: [],
  },
  {
    key: 'kci-schedules',
    name: 'Jadwal Keberangkatan KRL Per Stasiun',
    category: 'info',
    subcategory: 'kci',
    subcategoryLabel: 'Jadwal KRL Commuter Line',
    path: '/api/v1/kci/schedules',
    methods: ['GET'],
    summary: 'Jadwal KRL Per Stasiun',
    description: 'Mengambil jadwal lengkap jam keberangkatan KRL dari stasiun asal (contoh: BOO, MRI, JAKK, CKR).',
    card: { tag: 'KRL Commuter' },
    params: [
      { key: 'stationId', in: 'query', required: true, type: 'text', label: 'Kode Stasiun', default: 'BOO', placeholder: 'contoh: BOO (Bogor), MRI (Manggarai)', description: 'Kode stasiun KRL' },
      { key: 'timeFrom', in: 'query', type: 'text', label: 'Jam Mulai', default: '06:00', placeholder: 'HH:MM', description: 'Batas awal jam' },
      { key: 'timeTo', in: 'query', type: 'text', label: 'Jam Akhir', default: '22:00', placeholder: 'HH:MM', description: 'Batas akhir jam' },
    ],
  },
  {
    key: 'kci-route',
    name: 'Rute & Perhentian Kereta KRL',
    category: 'info',
    subcategory: 'kci',
    subcategoryLabel: 'Jadwal KRL Commuter Line',
    path: '/api/v1/kci/route',
    methods: ['GET'],
    summary: 'Rute Perhentian KRL',
    description: 'Mengambil seluruh stasiun perhentian & estimasi jam tiba untuk nomor kereta KRL tertentu.',
    card: { tag: 'KRL Commuter' },
    params: [
      { key: 'trainId', in: 'query', required: true, type: 'text', label: 'Nomor KA / Train ID', default: '1009', placeholder: 'contoh: 1009', description: 'Nomor KA KRL' },
    ],
  },

  // ================= GAME & SHOWCASE (ENKA NETWORK) =================
  {
    key: 'enka-profile',
    name: 'Enka Network Genshin / HSR Player Showcase',
    category: 'info',
    subcategory: 'enka',
    subcategoryLabel: 'Genshin & HSR Showcase',
    path: '/api/v1/enka/profile/1810139094',
    methods: ['GET'],
    summary: 'Enka Genshin/HSR Showcase',
    description: 'Mengekstrak profil player, nickname, level, achievement, list karakter showcase, artefak, dan weapon dari Enka Network berdasarkan UID.',
    card: { tag: 'Enka Network' },
    params: [
      { key: 'uid', in: 'path', required: true, type: 'text', label: 'UID Game', default: '1810139094', placeholder: 'contoh: 1810139094', description: 'UID Genshin Impact / Star Rail' },
    ],
  },

  // ================= TOOLS & UTILITIES =================
  {
    key: 'tempmail-create',
    name: 'Buat Email Sementara (TempMail)',
    category: 'info',
    subcategory: 'tempmail',
    subcategoryLabel: 'Temp Mail Generator',
    path: '/api/v1/tempmail/create',
    methods: ['GET'],
    summary: 'Generate Temp Mail',
    description: 'Membuat alamat email sementara instan (via Mail.tm) lengkap dengan password untuk verifikasi akun.',
    card: { tag: 'Temp Mail' },
    params: [],
  },
  {
    key: 'tempmail-messages',
    name: 'Cek Kotak Masuk Email (Inbox)',
    category: 'info',
    subcategory: 'tempmail',
    subcategoryLabel: 'Temp Mail Generator',
    path: '/api/v1/tempmail/messages',
    methods: ['GET'],
    summary: 'Inbox Temp Mail',
    description: 'Mengekstrak daftar pesan/OTP yang masuk ke alamat email tempmail.',
    card: { tag: 'Temp Mail' },
    params: [
      { key: 'email', in: 'query', required: true, type: 'text', label: 'Email', placeholder: 'alamat email tempmail', description: 'Email tempmail' },
      { key: 'password', in: 'query', required: true, type: 'text', label: 'Password', placeholder: 'password tempmail', description: 'Password tempmail' },
    ],
  },
  {
    key: 'upload-file',
    name: 'File & Image Uploader',
    category: 'info',
    subcategory: 'upload',
    subcategoryLabel: 'File Uploader',
    path: '/api/v1/upload',
    methods: ['POST'],
    summary: 'File Uploader',
    description: 'Mengunggah file/gambar (Cloudflare R2 storage / fallback local) dan menghasilkan direct URL publik.',
    card: { tag: 'Uploader' },
    params: [],
  },
  {
    key: 'server-stats',
    name: 'Statistik & Status Server Realtime',
    category: 'info',
    subcategory: 'system',
    subcategoryLabel: 'System Stats',
    path: '/api/v1/stats',
    methods: ['GET'],
    summary: 'Server Stats (Non-Secret)',
    description: 'Mengekstrak data statistik publik server (uptime, memori RSS/heap, load average, versi Node.js, & CPU cores).',
    card: { tag: 'System' },
    params: [],
  },

  // ================= DATA PENDIDIKAN =================
  {
    key: 'pddikti-info',
    name: 'Informasi API PDDIKTI',
    category: 'pendidikan',
    path: '/api/v1/pddikti',
    methods: ['GET'],
    summary: 'Informasi Endpoint PDDIKTI',
    description: 'Menampilkan informasi ringkas dan daftar endpoint yang tersedia untuk mengakses data publik PDDIKTI Kemdiktisaintek.',
    card: { tag: 'PDDIKTI' },
    params: [],
  },
  {
    key: 'pddikti-search',
    name: 'Pencarian Data PDDIKTI',
    category: 'pendidikan',
    path: '/api/v1/pddikti/search',
    methods: ['GET'],
    summary: 'Cari Mahasiswa, Dosen, PT & Prodi',
    description: 'Mencari data mahasiswa, dosen, perguruan tinggi, dan program studi di PDDIKTI berdasarkan kata kunci.',
    card: { tag: 'PDDIKTI' },
    params: [
      { key: 'q', in: 'query', required: true, type: 'text', label: 'Kata Kunci', default: 'Universitas Indonesia', placeholder: 'nama mahasiswa, dosen, kampus, atau prodi', description: 'Kata kunci pencarian PDDIKTI' },
      { key: 'tipe', in: 'query', type: 'select', options: ['all', 'mhs', 'dosen', 'pt', 'prodi'], label: 'Tipe Data', default: 'all', description: 'Batasi hasil berdasarkan tipe data' },
    ],
  },
  {
    key: 'pddikti-mahasiswa',
    name: 'Detail Mahasiswa PDDIKTI',
    category: 'pendidikan',
    path: '/api/v1/pddikti/mahasiswa/{id}',
    methods: ['GET'],
    summary: 'Detail Mahasiswa',
    description: 'Mengambil detail mahasiswa menggunakan encrypted ID yang diperoleh dari hasil pencarian PDDIKTI.',
    card: { tag: 'PDDIKTI' },
    params: [
      { key: 'id', in: 'path', required: true, type: 'text', label: 'Encrypted ID Mahasiswa', placeholder: 'encrypted ID dari hasil pencarian', description: 'Encrypted ID mahasiswa dari endpoint pencarian' },
    ],
  },
  {
    key: 'pddikti-detail',
    name: 'Detail Entitas PDDIKTI',
    category: 'pendidikan',
    path: '/api/v1/pddikti/detail/{tipe}/{id}',
    methods: ['GET'],
    summary: 'Detail Mahasiswa, Dosen, PT atau Prodi',
    description: 'Mengambil detail entitas PDDIKTI berdasarkan tipe data dan encrypted ID dari hasil pencarian.',
    card: { tag: 'PDDIKTI' },
    params: [
      { key: 'tipe', in: 'path', required: true, type: 'select', options: ['mhs', 'dosen', 'pt', 'prodi'], label: 'Tipe Data', default: 'mhs', description: 'Tipe entitas PDDIKTI' },
      { key: 'id', in: 'path', required: true, type: 'text', label: 'Encrypted ID', placeholder: 'encrypted ID dari hasil pencarian', description: 'Encrypted ID entitas dari endpoint pencarian' },
    ],
  },
  {
    key: 'pddikti-sub',
    name: 'Subdata Entitas PDDIKTI',
    category: 'pendidikan',
    path: '/api/v1/pddikti/sub/{tipe}/{data_type}/{id}',
    methods: ['GET'],
    summary: 'Subdata Dosen, PT atau Prodi',
    description: 'Mengambil kelompok data lanjutan suatu entitas PDDIKTI berdasarkan tipe entitas, jenis subdata, dan encrypted ID.',
    card: { tag: 'PDDIKTI' },
    params: [
      { key: 'tipe', in: 'path', required: true, type: 'select', options: ['pt', 'prodi', 'dosen'], label: 'Tipe Data', default: 'pt', description: 'Tipe entitas PDDIKTI yang menyediakan subdata' },
      { key: 'data_type', in: 'path', required: true, type: 'text', label: 'Jenis Subdata', default: 'jumlah-mahasiswa', placeholder: 'contoh: jumlah-mahasiswa atau study-history', description: 'Jenis subdata yang tersedia untuk tipe entitas terpilih' },
      { key: 'id', in: 'path', required: true, type: 'text', label: 'Encrypted ID', placeholder: 'encrypted ID dari hasil pencarian', description: 'Encrypted ID entitas dari endpoint pencarian' },
    ],
  },

  // ================= MEDIA DOWNLOADER =================
  {
    key: 'pinterest',
    name: 'Pinterest Image & Video Downloader',
    category: 'downloader',
    subcategory: 'pinterest',
    subcategoryLabel: 'Pinterest Downloader',
    path: '/api/v1/pinterest',
    methods: ['GET'],
    summary: 'Pinterest Downloader',
    description: 'Mengekstrak URL media gambar beresolusi tinggi (736x) dan video HD dari pin Pinterest.',
    card: { tag: 'Pinterest' },
    params: [
      urlParam('https://pin.it/4H3j456', 'https://pin.it/... atau https://www.pinterest.com/pin/...', 'URL Pin Pinterest'),
    ],
  },
  {
    key: 'instagram',
    name: 'Instagram Downloader (Post / Reel)',
    category: 'downloader',
    path: '/api/v1/instagram',
    methods: ['GET'],
    summary: 'Instagram Downloader',
    description: 'Mengekstrak URL media beresolusi tinggi (foto, video, reels, carousel) dari postingan Instagram.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://www.instagram.com/p/DFzL1234567/', 'https://www.instagram.com/p/...', 'URL Instagram'),
    ],
  },
  {
    key: 'fbdl',
    name: 'Facebook Video Downloader (fbdl)',
    category: 'downloader',
    path: '/api/v1/fbdl',
    methods: ['GET'],
    summary: 'Facebook Video Downloader',
    description: 'Mengekstrak link unduhan video HD dan SD langsung dari postingan/watch Facebook.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://www.facebook.com/watch/?v=123456789', 'https://www.facebook.com/watch/?v=...', 'URL Facebook Video'),
    ],
  },
  {
    key: 'threads',
    name: 'Threads Media Downloader',
    category: 'downloader',
    path: '/api/v1/threads',
    methods: ['GET'],
    summary: 'Threads Media Downloader',
    description: 'Mengekstrak media foto dan video dari postingan Meta Threads tanpa login wall.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://www.threads.net/@user/post/DFzL1234567', 'https://www.threads.net/@user/post/...', 'URL Threads Post'),
    ],
  },
  {
    key: 'ytdl',
    name: 'YouTube Video & Audio Downloader (ytdl - Server 1 YTMP3)',
    category: 'downloader',
    path: '/api/v1/ytdl',
    methods: ['GET'],
    summary: 'YouTube MP3 & MP4 Downloader (Server 1)',
    description: 'Mengonversi video/Shorts YouTube ke format MP3 (Audio) atau MP4 (Video) via YTMP3.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://youtu.be/dQw4w9WgXcQ', 'https://youtu.be/...', 'URL / Video ID YouTube'),
      {
        key: 'format',
        in: 'query',
        type: 'select',
        options: [
          { value: 'mp4', label: 'MP4 (Video)' },
          { value: 'mp3', label: 'MP3 (Audio)' },
        ],
        label: 'Format / Media',
        default: 'mp4',
        description: 'Pilihan format keluaran (mp3 atau mp4)',
      },
    ],
  },
  {
    key: 'ytdl2',
    name: 'YouTube Video Downloader (ytdl2 - Server 2 HD)',
    category: 'downloader',
    path: '/api/v1/ytdl2',
    methods: ['GET'],
    summary: 'YouTube Video Downloader (Server 2)',
    description: 'Mengonversi video/Shorts YouTube ke format MP4 HD (Engine 2 / Loader.to).',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://youtu.be/dQw4w9WgXcQ', 'https://youtu.be/...', 'URL / Video ID YouTube'),
      { key: 'quality', in: 'query', type: 'select', options: YT_QUALITIES, label: 'Kualitas Video', default: '720', description: 'Resolusi video yang diminta' },
    ],
  },
  {
    key: 'ytdl3',
    name: 'YouTube Video Downloader (ytdl3 - Server 3 4KDownload)',
    category: 'downloader',
    path: '/api/v1/ytdl3',
    methods: ['GET'],
    summary: 'YouTube Video Downloader (Server 3)',
    description: 'Mengonversi video/Shorts YouTube ke format MP4 (Engine 3 / 4KDownload).',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://youtu.be/dQw4w9WgXcQ', 'https://youtu.be/...', 'URL / Video ID YouTube'),
      { key: 'quality', in: 'query', type: 'select', options: YT_QUALITIES, label: 'Kualitas Video', default: '720', description: 'Resolusi video yang diminta' },
    ],
  },
  {
    key: 'twitter',
    name: 'Twitter/X Media Downloader',
    category: 'downloader',
    path: '/api/v1/twitter',
    methods: ['GET'],
    summary: 'Twitter/X Media Downloader',
    description: 'Mengekstrak foto dan video beresolusi tinggi dari Tweet Twitter/X via public syndication.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://x.com/jack/status/20', 'https://x.com/user/status/...', 'URL / ID Tweet'),
    ],
  },
  {
    key: 'tiktok',
    name: 'TikTok Video Downloader',
    category: 'downloader',
    path: '/api/v1/tiktok',
    methods: ['GET'],
    summary: 'TikTok Video Downloader',
    description: 'Mengekstrak URL video HD tanpa watermark, audio MP3, dan thumbnail dari video TikTok.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://vt.tiktok.com/ZSY123456/', 'https://vt.tiktok.com/...', 'URL TikTok Video'),
    ],
  },
  {
    key: 'tiktok2',
    name: 'TikTok Video Downloader (Server 2 - Snaptik)',
    category: 'downloader',
    path: '/api/v1/tiktok2',
    methods: ['GET', 'POST'],
    summary: 'TikTok Video Downloader via Snaptik',
    description: 'Mengekstrak URL video HD tanpa watermark, audio MP3, statistik, dan info author dari video TikTok via Snaptik.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://www.tiktok.com/@oppacoinsurabaya/video/7653693032440663314', 'https://www.tiktok.com/@.../video/...', 'URL TikTok Video'),
    ],
  },
  {
    key: 'mediafire',
    name: 'Mediafire File Downloader',
    category: 'downloader',
    path: '/api/v1/mediafire',
    methods: ['GET'],
    summary: 'Mediafire File Downloader',
    description: 'Mengekstrak direct download link serta ukuran file langsung dari halaman Mediafire.',
    card: { tag: 'Downloader' },
    params: [
      urlParam('https://www.mediafire.com/file/example/file.zip/file', 'https://www.mediafire.com/file/...', 'URL Mediafire File'),
    ],
  },
];
